{"name": "除法运算-异常:100/s", "status": "passed", "steps": [{"name": "1. 处理typeError异常。", "status": "passed", "start": 1624428042193, "stop": 1624428042193}], "attachments": [{"name": "log", "source": "1120a228-2e2e-41b9-aa5a-14a0c7017bb9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "'s'"}, {"name": "expect", "value": "0"}], "start": 1624428042180, "stop": 1624428042193, "uuid": "434e435d-2958-4c36-9d54-0b681ecea7bd", "historyId": "74ed5fb797eb8616074436624fe9c858", "testCaseId": "86bdf1d3b5df90ee666d9c0184f304cf", "fullName": "test_calculator.TestCalculator#test_div_Error", "labels": [{"name": "feature", "value": "加法和除法运算"}, {"name": "story", "value": "除法运算-异常处理"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "QKFZ-888"}, {"name": "thread", "value": "8080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}